
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action yesAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HPaned hpaned1;

	private global::Gtk.Button BtnClear;

	private global::Gtk.Button BtnRemoveBreaks;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView TextboxUserEntry;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView TextboxProgramOutput;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.yesAction = new global::Gtk.Action("yesAction", null, null, "gtk-yes");
		w1.Add(this.yesAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.WidthRequest = 640;
		this.HeightRequest = 480;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Remove Line Breaks");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned();
		this.hpaned1.HeightRequest = 40;
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 320;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.BtnClear = new global::Gtk.Button();
		this.BtnClear.CanFocus = true;
		this.BtnClear.Name = "BtnClear";
		this.BtnClear.UseUnderline = true;
		this.BtnClear.Label = global::Mono.Unix.Catalog.GetString("Clear Text");
		this.hpaned1.Add(this.BtnClear);
		global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.BtnClear]));
		w2.Resize = false;
		w2.Shrink = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.BtnRemoveBreaks = new global::Gtk.Button();
		this.BtnRemoveBreaks.CanFocus = true;
		this.BtnRemoveBreaks.Name = "BtnRemoveBreaks";
		this.BtnRemoveBreaks.UseUnderline = true;
		this.BtnRemoveBreaks.Label = global::Mono.Unix.Catalog.GetString("Remove Breaks");
		this.hpaned1.Add(this.BtnRemoveBreaks);
		global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.BtnRemoveBreaks]));
		w3.Resize = false;
		w3.Shrink = false;
		this.vbox1.Add(this.hpaned1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hpaned1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.TextboxUserEntry = new global::Gtk.TextView();
		this.TextboxUserEntry.HeightRequest = 220;
		this.TextboxUserEntry.CanFocus = true;
		this.TextboxUserEntry.Name = "TextboxUserEntry";
		this.GtkScrolledWindow.Add(this.TextboxUserEntry);
		this.vbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w6.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.TextboxProgramOutput = new global::Gtk.TextView();
		this.TextboxProgramOutput.HeightRequest = 220;
		this.TextboxProgramOutput.CanFocus = true;
		this.TextboxProgramOutput.Name = "TextboxProgramOutput";
		this.GtkScrolledWindow1.Add(this.TextboxProgramOutput);
		this.vbox1.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow1]));
		w8.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 640;
		this.DefaultHeight = 480;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.BtnClear.Clicked += new global::System.EventHandler(this.OnBtnClearClicked);
		this.BtnRemoveBreaks.Clicked += new global::System.EventHandler(this.OnBtnRemoveBreaksClicked);
	}
}
